stages:
  - test

check_lang:
  stage: test
  image: node:latest
  script:
    - python check_lang.py res/language/de.js res/language/en.js

eslint:
  stage: test
  image: node:latest
  before_script:
   - npm install
  script:
    - npm run eslint

stylelint:
  stage: test
  image: node:latest
  before_script:
   - npm install
  script:
    - npm run stylelint
